### ISSUE TITLE
Warning: unexpected database modification

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-local_moodlecheck#102]
I get an unexpected database modification warning when running PHPUnit tests:
```
local_moodlecheck\moodlecheck_rules_test::test_constantclass
Warning: unexpected database modification, resetting DB state
Warning: unexpected change of $USER

lib/phpunit/classes/util.php:299
lib/phpunit/classes/advanced_testcase.php:534
lib/phpunit/classes/advanced_testcase.php:132
```
Perhaps the setup function should have a $this->resetAfterTest(); line?

Moodle 4.0.5+ (Build: 20221222)
Php: 8.0.26, pgsql: 13.6, OS: Linux 5.15.0-56-generic x86_64
PHPUnit 9.5.26

**Comment by stronk7** [comment]
Wow, never have seen that before (neither locally or travis/gha). Those tests don't play with `$USER` at all, AFAIK.

Which is you exact phpunit command? Only local/moodlecheck or whole moodle ? Just trying to reproduce it here.

Ciao :-)

**Comment by stronk7** [comment]
Could it be that the test causing the problem is exactly the one executed BEFORE `local_moodlecheck\moodlecheck_rules_test::test_constantclass` ?

I'd suggest to use the very same phpunit command that was executed when you got the error, but adding the `--testdox` option. That way you can see what's executed immediately before the "Constantclass" one.

Ciao :-)

**Comment by ewallah** [comment]
The test causing the problem was indeed exactly before the local_moodlecheck test (local-m****)

So sorry for the wrong warning, but thanks for the excellent feedback!
