### ISSUE TITLE
Plugin local_moodlecheck does not declare valid $plugin->component in its version.php.

### ISSUE THREAD

**Issue by scara** [moodlehq/moodle-local_moodlecheck#26]
Read about the details in https://tracker.moodle.org/browse/MDL-48494.
This is the stack trace:
```
line 304 of /lib/classes/plugin_manager.php: call to debugging()
line 324 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 208 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 134 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 90 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 384 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 344 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 858 of /admin/renderer.php: call to core_plugin_manager->get_plugins()
line 221 of /admin/renderer.php: call to core_admin_renderer->plugins_check_table()
line 346 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
```

**Comment by danpoltawski** [comment]
Fixed by #25 ? I guess the problem is that we've not released this on plugins directory yet?

**Comment by scara** [comment]
Yep: shame on me, apologies for the noise.
Not sure about the directory: I use it straight from this repo and I was "actually sure" to have updated it.

**Comment by stronk7** [comment]
There is nothing "sure" in life.

Disclaimer: I faced exactly the same problem, went and create a patch locally, did a master pull and rebased, just to find my patch disappearing because the very same change was already in master (by #25) @ github. In fact I became surprised about how git had dismissed my local patch completely without notice, never had happened that before.

So welcome to the club of the more repeated patch ever, lol.

Ciao :-)
